// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package store

import (
	"context"
)

const deleteThing = `-- name: DeleteThing :exec
DELETE FROM Things WHERE id=?
`

func (q *Queries) DeleteThing(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteThing, id)
	return err
}

const insertThing = `-- name: InsertThing :execlastid
INSERT INTO Things(Year, Month, Day, What) VALUES(?, ?, ?, ?)
`

type InsertThingParams struct {
	Year  int64
	Month int64
	Day   int64
	What  string
}

func (q *Queries) InsertThing(ctx context.Context, arg InsertThingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertThing,
		arg.Year,
		arg.Month,
		arg.Day,
		arg.What,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const listThings = `-- name: ListThings :many
SELECT id, what, year, month, day FROM Things
ORDER BY Year DESC, Month DESC, Day DESC
`

func (q *Queries) ListThings(ctx context.Context) ([]Thing, error) {
	rows, err := q.db.QueryContext(ctx, listThings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Thing
	for rows.Next() {
		var i Thing
		if err := rows.Scan(
			&i.ID,
			&i.What,
			&i.Year,
			&i.Month,
			&i.Day,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopThings = `-- name: ListTopThings :many
SELECT COUNT(*) as cnt, What FROM Things
GROUP BY What
ORDER BY cnt DESC
LIMIT 10
`

type ListTopThingsRow struct {
	Cnt  int64
	What string
}

func (q *Queries) ListTopThings(ctx context.Context) ([]ListTopThingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTopThings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTopThingsRow
	for rows.Next() {
		var i ListTopThingsRow
		if err := rows.Scan(&i.Cnt, &i.What); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
